POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video 01",
    "description": "Esse é o primeiro video",
    "duration": 100
}

###

GET http://localhost:3333/videos?search=01

###

PUT http://localhost:3333/videos/9896f962-536a-4b16-8292-cb58be69fb7a
Content-Type: application/json

{
    "title": "Video 02",
    "description": "Esse é o primeiro video",
    "duration": 100
}

###

DELETE http://localhost:3333/videos/8c719eb5-3e82-4282-abbb-24ca9c4c0cd3